-- Migration V4: Create roles and permissions structure
-- Description: Creates tables for role-based access control (RBAC) system

-- =====================================================
-- 1. CREATE ROLES TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- Index on role name for fast lookups
CREATE INDEX IF NOT EXISTS idx_roles_name ON roles (name);

-- =====================================================
-- 2. CREATE PERMISSIONS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module VARCHAR(100) NOT NULL,
    action VARCHAR(20) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_module_action UNIQUE (module, action)
);

-- Index on module for filtering by module
CREATE INDEX IF NOT EXISTS idx_permissions_module ON permissions (module);

-- Index on action for filtering by action
CREATE INDEX IF NOT EXISTS idx_permissions_action ON permissions (action);

-- Composite index on module and action for permission checks
CREATE INDEX IF NOT EXISTS idx_permissions_module_action ON permissions (module, action);

-- =====================================================
-- 3. CREATE ROLE_PERMISSIONS JOIN TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    granted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

-- Index on role_id for fast lookups when checking permissions
CREATE INDEX IF NOT EXISTS idx_role_permissions_role_id ON role_permissions (role_id);

-- Index on permission_id for reverse lookups
CREATE INDEX IF NOT EXISTS idx_role_permissions_permission_id ON role_permissions (permission_id);

-- =====================================================
-- 4. UPDATE SORUMLU TABLE - ADD ROLE REFERENCE
-- =====================================================
ALTER TABLE sorumlu ADD COLUMN IF NOT EXISTS role_id BIGINT;

-- Add foreign key constraint (if not exists - H2 will ignore if exists)
-- Note: H2 doesn't support ADD CONSTRAINT IF NOT EXISTS, so we skip if error

-- Index on role_id for performance
CREATE INDEX IF NOT EXISTS idx_sorumlu_role_id ON sorumlu (role_id);

-- =====================================================
-- 5. INSERT DEFAULT ROLES (MERGE to avoid duplicates)
-- =====================================================
MERGE INTO roles (name, description)
KEY (name)
VALUES 
    ('ADMIN', 'Administrator with full system access'),
    ('STAFF', 'Staff member with limited access to manage their own areas'),
    ('READONLY', 'Read-only access to view information');

-- =====================================================
-- 6. INSERT DEFAULT PERMISSIONS (MERGE to avoid duplicates)
-- =====================================================

-- EDUCATION MODULE
MERGE INTO permissions (module, action, description) KEY (module, action) VALUES
    ('education', 'view', 'View education records'),
    ('education', 'create', 'Create new education records'),
    ('education', 'update', 'Update existing education records'),
    ('education', 'delete', 'Delete education records');

-- TRAINER MODULE
MERGE INTO permissions (module, action, description) KEY (module, action) VALUES
    ('trainer', 'view', 'View trainer records'),
    ('trainer', 'create', 'Create new trainer records'),
    ('trainer', 'update', 'Update existing trainer records'),
    ('trainer', 'delete', 'Delete trainer records');

-- RESPONSIBLE MODULE
MERGE INTO permissions (module, action, description) KEY (module, action) VALUES
    ('responsible', 'view', 'View responsible person records'),
    ('responsible', 'create', 'Create new responsible person records'),
    ('responsible', 'update', 'Update existing responsible person records'),
    ('responsible', 'delete', 'Delete responsible person records');

-- CATEGORY MODULE
MERGE INTO permissions (module, action, description) KEY (module, action) VALUES
    ('category', 'view', 'View category records'),
    ('category', 'create', 'Create new category records'),
    ('category', 'update', 'Update existing category records'),
    ('category', 'delete', 'Delete category records');

-- STAKEHOLDER MODULE
MERGE INTO permissions (module, action, description) KEY (module, action) VALUES
    ('stakeholder', 'view', 'View stakeholder records'),
    ('stakeholder', 'create', 'Create new stakeholder records'),
    ('stakeholder', 'update', 'Update existing stakeholder records'),
    ('stakeholder', 'delete', 'Delete stakeholder records');

-- PROJECT MODULE
MERGE INTO permissions (module, action, description) KEY (module, action) VALUES
    ('project', 'view', 'View project records'),
    ('project', 'create', 'Create new project records'),
    ('project', 'update', 'Update existing project records'),
    ('project', 'delete', 'Delete project records');

-- ACTIVITY MODULE
MERGE INTO permissions (module, action, description) KEY (module, action) VALUES
    ('activity', 'view', 'View activity records'),
    ('activity', 'create', 'Create new activity records'),
    ('activity', 'update', 'Update existing activity records'),
    ('activity', 'delete', 'Delete activity records');

-- PAYMENT MODULE
MERGE INTO permissions (module, action, description) KEY (module, action) VALUES
    ('payment', 'view', 'View payment records'),
    ('payment', 'create', 'Create new payment records'),
    ('payment', 'update', 'Update existing payment records'),
    ('payment', 'delete', 'Delete payment records');

-- LOGS MODULE
MERGE INTO permissions (module, action, description) KEY (module, action) VALUES
    ('logs', 'view', 'View system logs'),
    ('logs', 'manage', 'Manage and delete system logs');

-- =====================================================
-- 7. ASSIGN PERMISSIONS TO ROLES
-- =====================================================

-- ADMIN: Full access to everything (only insert if not exists)
MERGE INTO role_permissions (role_id, permission_id)
KEY (role_id, permission_id)
SELECT r.id, p.id 
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'ADMIN';

-- STAFF: Can view, create, and update (but not delete) most modules
MERGE INTO role_permissions (role_id, permission_id)
KEY (role_id, permission_id)
SELECT r.id, p.id 
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'STAFF'
AND (
    (p.action IN ('view', 'create', 'update') AND p.module IN ('education', 'trainer', 'responsible', 'category', 'stakeholder', 'project', 'activity', 'payment'))
    OR (p.action = 'view' AND p.module = 'logs')
);

-- READONLY: Can only view all modules
MERGE INTO role_permissions (role_id, permission_id)
KEY (role_id, permission_id)
SELECT r.id, p.id 
FROM roles r
CROSS JOIN permissions p
WHERE r.name = 'READONLY'
AND p.action = 'view';

-- =====================================================
-- 8. SET DEFAULT ROLE FOR EXISTING SORUMLU RECORDS
-- =====================================================
-- Set all existing responsible persons to STAFF role by default
UPDATE sorumlu 
SET role_id = (SELECT id FROM roles WHERE name = 'STAFF')
WHERE role_id IS NULL;
